%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   A complete workflow of flicker assessment using MATLAB functions and 
%   Simulink block (Digital flickermeter). 
% 
% Parameters
% -----------
%   Sr: double 
%       Rated apparent power of the marine energy converter (VA).
%   Un: double 
%       RMS value of the nomianal voltage of the grid (V).
%   In: double 
%       Nominal current (A).
%   fg: double 
%       Nominal grid frequency, 60Hz or 50Hz.
%   fs: double 
%       Sampling frequency (Hz), used in gen_test_data().
%   fm: double 
%       Modulating frequency for current used in gen_test_data().
%   fv: double 
%       Modulating frequency for voltage used in gen_test_data().
%   DeltaI_I: double array (4) 
%       Relative current changes (%) according to Table B.2 and Table B.3
%       in IECTS61400-21-1, used in gen_test_data()
%   opt: int 
%       Option number used in gen_test_data(). 
%   T: double 
%       Duration (s) used in gen_test_data().
%   SCR: double 
%       Short-circuit ratio, SCR = S_kfic/Sr
%   u_m: struct() 
%       u_m(t) is the measured instantaneous voltage (V)
%       .time: time at each measurement (s)
%       .data: array of size (ntime) measured instantaneous voltage (V).
%   i_m: struct()
%       i_m(t) is the measured instantaneous current (A)
%       .time: time at each measurement
%       .data: array of size (ntime, 4) measured instantaneous current (A)
%       at impedance phase angles = 30, 50, 70, 85.
%   method: string 
%       Method used to calculate fundamental frequency of u_m, 'zcd' or 'stft'
%   methodopts: cell array 
%       Name-value arguments for STFT method.
%   u_fic: double array (ntime,4) 
%       Instantaneous phase-to-neutral voltage simulated at fictitious 
%       grid (V) for impedence angles = 30, 50, 70, 85
%   P_stfic: double 
%       Flicker emission on the fictitious grid. 
%   coef_flicker: double 
%       Flicker coefficient for continuous operation
% Note
% -------
% Step 0. Prep data. Set Sr, Un, In, SCR, fg, & fs. 
%       u_m and i_m can be generated by calling gen_test_data() or read
%       from observations (OBS).
%
% Step 1-3. Calculate u_fic from i_m and u_m by calling flicker_ufic().
%
% Step 4. Calculate P_stfic from u_fic by running Digital Flickermeter in
%       MATLAB Simulink (ref: IECTS61000-4-15).
% 
% Step 5. Calculate coef_flicker from P_stfic according to Eq (6) in
%       IECTS62600-30.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Step 0. prepare data needed: 
% u_m, i_m, Sr, Un, In, SCR, fg, & fs
Un=12e3; In=144; fg=60; fs=50e3; Sr = 3e6; SCR=20; 
% opt1: generate test data:
fm = 25;% modulating frequency for current
fv = 0.5;% modulating frequency for voltage
% DeltaI_I = [0 0 0 0];% pure sine wave
% DeltaI_I = [8.040 9.376 11.479 12.844];%TableB.3,fg=60,SCR=50,fm=33.3
DeltaI_I = [4.763 5.726 7.640 9.488];   %TableB.2,fg=60,SCR=20,fm=25
% DeltaI_I = [3.212 3.958 5.644 7.711]; %TableB.2,fg=60,SCR=20,fm=20
opt=5; T=650;
[i_m,u_m]=gen_test_data(Un,In,fg,fs,fm,fv,DeltaI_I,opt,T);
% opt 2: OBS data with necessary data cleanings. 

%% Step 1-3. call flicker_ufic() to calculate u_fic from i_m and u_m.
[~,~,~,~,~,~,u_fic] = flicker_ufic(...
    Sr,Un,SCR,fg,u_m,i_m,method,methodopts);
% check u0 to make sure it fullfills the requirements in the IECTS
% hold off; plot(u_m.time,u_m.data);hold on; grid on;
% plot(u_m.time,u0);legend('um','u0');xlim([10,10.5])
%% Step 4. Calculate flicker emission (P_st,fic)
% check: run power_KALFlicker to get x_in, enable_in, & V_flicker_in
% 4.1 Prep input for Digital flickermeter: u_fic_in
disp(size(u_fic)); time = u_m.time;
u_fic_in = timeseries(u_fic(:,2),time);
% 4.2 Run Digital flickermeter in simulink to get S5
S5 = out.S5;
% 4.3 Calculate Pst
% open statistical analyzer for flickermeter
% P_stfic = ;
%% Step 5. Calculate flicker coefficient
Xfic = 2*pi*fg*Lfic;
S_kfic = (Un^2)./sqrt(Rfic.^2+Xfic.^2);
coef_flicker = calc_flicker_coefficient(P_stfic,S_kfic,Sr);

